# Generated by Django 2.2 on 2019-04-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20190409_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
