# Generated by Django 2.2 on 2019-04-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='realtor',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='realtor',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='realtor',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
